[0m15:05:57.365212 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000172CA8CCE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000172CD2F7110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000172CBBDB8F0>]}


============================== 15:05:57.377283 | e0233413-3d38-4470-b18a-b6ba0e574c1b ==============================
[0m15:05:57.377283 [info ] [MainThread]: Running with dbt=1.9.2
[0m15:05:57.380231 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\HP\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init DBT-Project', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:06:13.746173 [info ] [MainThread]: A project called telegram_dbt_project already exists here.
[0m15:06:13.749102 [debug] [MainThread]: Command `dbt init` succeeded at 15:06:13.749102 after 16.89 seconds
[0m15:06:13.750102 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000172CD490BF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000172CA7DCB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000172CD956960>]}
[0m15:06:13.751054 [debug] [MainThread]: Flushing usage events
[0m15:06:15.101356 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:07:00.179348 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C27647D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C20ABEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C2204380>]}


============================== 15:07:00.196364 | df5130aa-b922-42aa-963f-3e50a557fd8a ==============================
[0m15:07:00.196364 [info ] [MainThread]: Running with dbt=1.9.2
[0m15:07:00.200366 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\HP\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init DBT-Project', 'send_anonymous_usage_stats': 'True'}
[0m15:07:15.190354 [debug] [MainThread]: Starter project path: C:\Users\HP\Desktop\10 academy\Kara_Solutions_Telegram_Scrapper\venv\Lib\site-packages\dbt\include\starter_project
[0m15:07:15.274952 [info ] [MainThread]: 
Your new dbt project "telegram_dbt_project_final" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:07:15.281130 [info ] [MainThread]: Setting up your profile.
[0m15:07:15.292394 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m15:07:15.298593 [debug] [MainThread]: Command `dbt init` failed at 15:07:15.298593 after 15.52 seconds
[0m15:07:15.300086 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C22991F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C27B9EE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F6C27BA810>]}
[0m15:07:15.304160 [debug] [MainThread]: Flushing usage events
[0m15:07:16.461549 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:13:43.841174 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF313690D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF33BC34A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF3359BF50>]}


============================== 15:13:43.852692 | dace5d94-26a5-4850-a6d5-cde017966c4f ==============================
[0m15:13:43.852692 [info ] [MainThread]: Running with dbt=1.9.2
[0m15:13:43.855723 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\HP\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:13:43.857397 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\HP\Desktop\10 academy\Kara_Solutions_Telegram_Scrapper\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:13:43.860611 [debug] [MainThread]: Command `dbt run` failed at 15:13:43.860611 after 0.59 seconds
[0m15:13:43.862764 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF3307FB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF33A31730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BF33E20DA0>]}
[0m15:13:43.863770 [debug] [MainThread]: Flushing usage events
[0m15:13:45.123169 [debug] [MainThread]: An error was encountered while trying to flush usage events
